"""Add scraped_date and remove number

Revision ID: 5738b68839bc
Revises: f3a7ae1ce205
Create Date: 2025-08-13 13:10:29.286003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5738b68839bc'
down_revision: Union[str, Sequence[str], None] = 'f3a7ae1ce205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('scraped_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_players_scraped_date'), 'players', ['scraped_date'], unique=False)
    op.drop_column('players', 'number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('number', mysql.VARCHAR(length=10), nullable=True))
    op.drop_index(op.f('ix_players_scraped_date'), table_name='players')
    op.drop_column('players', 'scraped_date')
    # ### end Alembic commands ###
